### ISSUE TITLE
The function bigint_to_string will ramdonly produce some random value at the end on ios

### ISSUE THREAD

**Issue by crackerli** [MinaProtocol/c-reference-signer#5]
**First, I don't know if this issue is platform related, I can't produce it on android(but I don't know whether I have bad luck to produce it), but it usually happen on ios platform, run 4 times, will happen 1 time**

Below is my extended code for sign Transaction:
void native_sign_user_command_montgomery(
    uint8_t *sk,
    char *memo,
    char *fee_payer_address,
    char *sender_address,
    char *receiver_address,
    Currency fee,
    TokenId fee_token,
    Nonce nonce,
    GlobalSlot valid_until,
    TokenId token_id,
    Currency amount,
    bool token_locked,
    uint8_t transaction_type, // 0 for transaction, 1 for delegation
    char *out_field,
    uint8_t *field_length,
    char *out_scalar,
    uint8_t *scalar_length
) {
    Transaction txn;

    prepare_memo(txn.memo, memo);
    #ifdef ANDROID_LIB
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "memo=%s", memo);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "fee_payer_address=%s", fee_payer_address);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "sender_address=%s", sender_address);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "receiver_address=%s", receiver_address);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "fee=%lu", fee);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "fee_token=%lu", fee_token);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "nonce=%lu", nonce);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "valid_until=%lu", valid_until);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "token_id=%lu", token_id);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "amount=%lu", amount);
    __android_log_print(ANDROID_LOG_DEBUG, NATIVE_TAG, "token_locked=%d", token_locked);
    #else
    printf("memo=%s", memo);
    #endif

    txn.fee = fee;
    txn.fee_token = fee_token;
    read_public_key_compressed(&txn.fee_payer_pk, fee_payer_address);
    txn.nonce = nonce;
    txn.valid_until = valid_until;

    if(0 == transaction_type) {
        txn.tag[0] = 0;
        txn.tag[1] = 0;
        txn.tag[2] = 0;
        txn.amount = amount;
    } else {
        txn.tag[0] = 0;
        txn.tag[1] = 0;
        txn.tag[2] = 1;
        txn.amount = 0;
    }

    read_public_key_compressed(&txn.source_pk, sender_address);
    read_public_key_compressed(&txn.receiver_pk, receiver_address);
    txn.token_id = token_id;
    txn.token_locked = false;

    Keypair kp;
    scalar_copy(kp.priv, sk);
    generate_pubkey(&kp.pub, sk);

    Signature sig;
    sign(&sig, &kp, &txn);

    char field_str[DIGITS] = { 0 };
    char scalar_str[DIGITS] = { 0 };
    uint64_t tmp[4];
    memset(tmp, 0, sizeof(tmp));

    fiat_pasta_fp_from_montgomery(tmp, sig.rx);
    bigint_to_string(out_field, tmp);
    field_length[0] = strlen(out_field);
    printf("native field: %s\n", out_field);
    memset(tmp, 0, sizeof(tmp));
    fiat_pasta_fq_from_montgomery(tmp, sig.s);
    bigint_to_string(out_scalar, tmp);
    scalar_length[0] = strlen(out_scalar);
    printf("native scalar: %s\n", out_scalar);
}

**you can see I print the field and scalar of the signature, sometimes they have value like below:**
field="12312170045568262133191740641935826581405327991016510478708928455469559085398l"
scalar="8808314428735299562006218168432471183594581012126124120771370508650535502329("

**the testcases I used was:**
Future<bool> testSignDelegation3() async {
  Uint8List sk = MinaHelper.hexToBytes('2943fbbbcf63025456cfcebae3f481462b1e720d0c7d2a10d113fb6b1847cb3d');
  String memo = '';
  String feePayerAddress = 'B62qpkf1jH9sqtZy4kAJHgdChfuRX7SPqoX4Q2ZjJH2YDNWUUd92bxo';
  String senderAddress = 'B62qpkf1jH9sqtZy4kAJHgdChfuRX7SPqoX4Q2ZjJH2YDNWUUd92bxo';
  String receiverAddress = 'B62qpaDc8nfu4a7xghkEni8u2rBjx7EH95MFeZAhTgGofopaxFjdS7P';
  BigInt fee = BigInt.from(1202056900);
  BigInt feeToken = BigInt.from(1);
  int nonce = 0;
  int validUntil = 577216;
  BigInt tokenId = BigInt.from(1);
  int tokenLocked = 0;

  Signature signature = await signDelegation(MinaHelper.reverse(sk), memo, feePayerAddress,
      senderAddress, receiverAddress, fee, feeToken, nonce, validUntil, tokenId, tokenLocked);
  print('--signature rx=${signature.rx}--');
  print('--signature s=${signature.s}--');
  bool rxRet = signature.rx == '12312170045568262133191740641935826581405327991016510478708928455469559085398';
  bool sRet = signature.s == '8808314428735299562006218168432471183594581012126124120771370508650535502329';
  return rxRet && sRet;
}

**This test case is equal to ledger app test cases provided by Joseph, in unit_tests.py:**
    # Sign delegation tx (account 2, fee=1.2020569, nonce=0, valid_until=577216)
    # apdu=e00300000000015a0000000242363271706b66316a48397371745a79346b414a486764436866755258375350716f583451325a6a4a483259444e57555564393262786f4236327170614463386e66753461377867686b456e6938753272426a7837454839354d46655a41685467476f666f706178466a6453375000000000000000000000000047a5eec4000000000008cec0000000000000000000000000000000000000000000000000000000000000000004
    # sig=1b3870f89d0208740ab1284c00364f7f34949a9a823fd245e1d3d33e322679561379544c9002726386d11a04c5d58291b41af7cff516d809f77d8dda3e8cc1f9
    assert(mina.ledger_sign_tx(mina.TX_TYPE_DELEGATION,
                               2,
                               "B62qpkf1jH9sqtZy4kAJHgdChfuRX7SPqoX4Q2ZjJH2YDNWUUd92bxo",
                               "B62qpaDc8nfu4a7xghkEni8u2rBjx7EH95MFeZAhTgGofopaxFjdS7P",
                               0,
                               1202056900,
                               0,
                               577216,
                               "") == "1b3870f89d0208740ab1284c00364f7f34949a9a823fd245e1d3d33e322679561379544c9002726386d11a04c5d58291b41af7cff516d809f77d8dda3e8cc1f9")

**Comment by imeckler** [comment]
Fixed in #6
